export const provinceData = [
  "TPHCM",
  "BếnTre",
  "LongAn",
  "CầnThơ",
  "AnGiang",
  "TiềnGiang",
  "VũngTàu",
  "BìnhDương",
  "BìnhPhước",
  "TâyNinh",
  "LâmĐồng",
  "ĐắkLắk",
  "GiaLai",
  "QuảngNgãi",
];
export const cityData = {
  TPHCM: [
    "Quận 1",
    "Quận 12",
    "Thủ Đức",
    "Quận 9",
    "Gò Vấp",
    "Bình Thạnh",
    "Tân Phú",
    "Phú Nhuận",
    "Quận 2",
    "Quận 3",
    "Quận 10",
    "Quận 11",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 8",
    "Bình Tân",
    "Quận 7",
    "Củ Chi",
    "Hóc Môn",
    "Bình Chánh",
    "Nhà Bè",
    "Cần Giờ",
  ],
  BếnTre: [
    "Thành phố Bến Tre",
    "Châu Thành",
    "Chợ Lách",
    "Mỏ Cày Nam",
    "Giồng Trôm",
    "Bình Đại",
    "Ba Tri",
    "Thạnh Phú",
    "Mỏ Cày Bắc",
  ],
  LongAn: [
    "Thành phố Tân An",
    "Kiến Tường",
    "Tân Hưng",
    "Vĩnh Hưng",
    "Mộc Hóa",
    "Tân Thạnh",
    "Thạnh Hòa",
    "Đức Huệ",
    "Đức Hòa",
    "Bến Lức",
    "Thủ thừa",
    "Tân Trụ",
    "Cần Đước",
    "Cần Giuộc",
    "Châu Thành",
  ],
  CầnThơ: [
    "Ninh Kiều",
    "Ô Môn",
    "Bình Thủy",
    "Cái Răng",
    "Thốt Nốt",
    "Vĩnh Thạnh",
    "Cờ Đỏ",
    "Phong Điền",
    "Thới Lai",
    "TiềnGiang",
  ],
  AnGiang: [
    "Thành phố Long Xuyên",
    "Thành phố Châu Đốc",
    "An Phú",
    "Tân Châu",
    "Phú Tân",
    "Châu Phú",
    "Tịnh Biên",
    "Tri Tôn",
    "Châu Thành",
    "Chợ Mới",
    "Thoại Sơn",
  ],
  TiềnGiang: [
    "Thành phố Mỹ Tho",
    "Thị xã Gò Công",
    "Thị xã Cai Lậy",
    "Tân Phước",
    "Cái Bè",
    "Cai Lậy",
    "Châu Thành",
    "Chợ Gạo",
    "Gò Công Tây",
    "Gò Công Đông",
    "Tân Phú Đông",
  ],
  VũngTàu: [
    "Thành phố Vũng Tàu",
    "Thành phố Bà Rịa",
    "Châu Đức",
    "Xuyên Mộc",
    "Long Điền",
    "Đất Đỏ",
    "Tân Thành",
  ],
  BìnhDương: [
    "Thành phố Thủ Dầu Một",
    "Bàu Bàng",
    "Dầu Tiếng",
    "Thị xã Bến Cát",
    "Phú Giáo",
    "Thị xã Tân Uyên",
    "Thị xã Dĩ An",
    "Thị xã Thuận An",
    "Bắc Tân Uyên",
  ],
  BìnhPhước: [
    "Thị xã Phước Long",
    "Thị xã Đồng Xoài",
    "Thị xã Bình Long",
    "Bù Gia Mập",
    "Lộc Nih",
    "Bù Đốp",
    "Hớn Quản",
    "Đồng Phú",
    "Bù Đăng",
    "Chơn Thành",
    "Phú Riềng",
  ],
  TâyNinh: [
    "Thành phố Tây Ninh",
    "Tân Biên",
    "Tân Châu",
    "Dương Minh Châu",
    "Châu Thành",
    "Hòa Thành",
    "Gò Dầu",
    "Bến Cầu",
    "Trảng Bàng",
  ],
  LâmĐồng: [
    "Thành phố Đà Lạt",
    "Thành phố Bảo Lộc",
    "Đam Rông",
    "Lạc Dương",
    "Lâm Hà",
    "Đơn Dương",
    "Đức Trọng",
    "Di Linh",
  ],
  ĐắkLắk: [
    "Thành phố Buôn Ma Thuột",
    "Thị xã Buôn Hồ",
    "Thị xã Ea'Hleo",
    "Thị xã Ea Súp",
    "Buôn Đôn",
    "Cư M'gar",
    "Krông Búk",
    "Krông Năng",
    "Ea Kar",
    "M'Đrắk",
    "Krông Bông",
    "Krông Pắc",
    "Krông A Na",
    "Lắk",
    "Cư Kuin",
  ],
  GiaLai: [
    "Thành phố Pleiku",
    "Thị xã An Khê",
    "Thị xã Ayun Pa",
    "KBang",
    "Đăk Đoa",
    "Chư Păh",
    "la Grai",
    "Mang Yang",
    "Kông Chro",
    "Đức Cơ",
    "Chư Prông",
    "Chư Sê",
    "Đăk Pơ",
    "la Pa",
    "Krông Pa",
    "Phú Thiện",
    "Chư Pưh",
  ],
  QuảngNgãi: [
    "Thành phố Quảng Ngãi",
    "Bình Sơn",
    "Trà Bồng",
    "Tây Trà",
    "Sơn Tịnh",
    "Tư Nghĩa",
    "Sơn Hà",
    "Sơn Tây",
    "Minh Long",
    "Nghĩa Hành",
    "Mộ Đức",
    "Đức Phổ",
    "Ba Tơ",
    "Lý Sơn",
  ],
};
